-- Replace zk1 with your NetID

-- execute data setup script
@dataSetupScript06.sql

spool spool06.txt

PROMPT jy3555
/*

YOU START YOUR ANSWERS AFTER THE END OF THIS COMMENT BLOCK

ANSWER0 is an example to show you the structure of what you need to produce, unless instructed otherwise in the assignment. Please read carefully what you are asked to do.

Insert your solution for ANSWERX between the string -- ANSWERX and the string PROMPT ANSWERX

*/

-- Answer 0 represents a sample quert that uses the temp table TEMP0 just to demonstrate the usage of temp table.
-- ANSWER0
CREATE TABLE TEMP0
AS SELECT *
FROM SMALL;

CREATE TABLE ANSWER0
AS SELECT DISTINCT TIN
FROM TEMP0
ORDER BY TIN DESC;


PROMPT ANSWER0
SELECT * FROM ANSWER0;

-- ANSWER1
CREATE TABLE ANSWER1
AS SELECT DISTINCT REGNUMBER, TIN
FROM COMPANY
ORDER BY REGNUMBER ASC, TIN DESC;

PROMPT ANSWER1
SELECT * FROM ANSWER1;

-- ANSWER2
CREATE TABLE TEMP1 AS
SELECT DISTINCT TIN 
FROM COMPANY_DOMAIN
WHERE DOMAIN_NAME = 'IT';

CREATE TABLE TEMP2 AS
SELECT DISTINCT TEMP1.TIN 
FROM TEMP1, BIG
WHERE TEMP1.TIN = BIG.TIN
AND BIG.FAMILYNAME = 'Garcia';

CREATE TABLE ANSWER2 AS
SELECT DISTINCT COMPANY.REGNUMBER, COMPANY.TIN 
FROM TEMP2, COMPANY
WHERE TEMP2.TIN = COMPANY.TIN
ORDER BY REGNUMBER ASC, TIN ASC;

PROMPT ANSWER2
SELECT * FROM ANSWER2;

-- ANSWER3
CREATE TABLE TEMP3 AS
SELECT DISTINCT HELPED AS HELPER , HELPER AS HELPED
FROM HELPS;

CREATE TABLE ANSWER3 AS 
SELECT DISTINCT HELPER AS HELPERTIN, HELPED AS HELPEDTIN
FROM HELPS
INTERSECT 
SELECT DISTINCT HELPER AS HELPERTIN, HELPED AS HELPEDTIN
FROM TEMP3
ORDER BY HELPERTIN ASC, HELPEDTIN ASC;

PROMPT ANSWER3
SELECT * FROM ANSWER3;

-- ANSWER4
CREATE TABLE TEMP4 AS
SELECT TIN
FROM COMPANY_DOMAIN 
WHERE DOMAIN_NAME = 'IT';


CREATE TABLE TEMP5 AS 
SELECT DISTINCT HELPED AS HELPED_A
FROM HELPS
WHERE HELPER = '59515298'
INTERSECT
SELECT DISTINCT HELPED AS HELPED_A
FROM HELPS
WHERE HELPER = '51251930';

CREATE TABLE ANSWER4 AS
SELECT DISTINCT COMPANY.REGNUMBER, COMPANY.TIN
FROM COMPANY, TEMP4, TEMP5
WHERE COMPANY.TIN = TEMP4.TIN AND COMPANY.TIN = TEMP5.HELPED_A
ORDER BY REGNUMBER ASC, TIN ASC;

PROMPT ANSWER4
SELECT * FROM ANSWER4;

-- ANSWER5
CREATE TABLE TEMP6 AS
SELECT DISTINCT TIN
FROM COMPANY
MINUS
SELECT DISTINCT HELPER AS TIN
FROM HELPS;

CREATE TABLE ANSWER5 AS 
SELECT DISTINCT COMPANY.REGNUMBER, COMPANY.TIN
FROM COMPANY, TEMP6
WHERE COMPANY.TIN = TEMP6.TIN
ORDER BY REGNUMBER ASC, TIN ASC;

PROMPT ANSWER5
SELECT * FROM ANSWER5;

-- ANSWER6
CREATE TABLE TEMP7 AS
SELECT DISTINCT TIN
FROM COMPANY_DOMAIN
WHERE DOMAIN_NAME != 'IT';

CREATE TABLE ANSWER6 AS
SELECT DISTINCT COMPANY.REGNUMBER, COMPANY.TIN
FROM COMPANY, TEMP7
WHERE COMPANY.TIN = TEMP7.TIN
ORDER BY REGNUMBER ASC, TIN ASC;
PROMPT ANSWER6
SELECT * FROM ANSWER6;

-- ANSWER7
CREATE TABLE TEMP8 AS
SELECT SMALL.TIN 
FROM SMALL, COMPANY_DOMAIN
WHERE SMALL.TIN = COMPANY_DOMAIN.TIN
AND COMPANY_DOMAIN.DOMAIN_NAME = 'IT' 
INTERSECT
SELECT SMALL.TIN 
FROM SMALL, COMPANY_DOMAIN
WHERE SMALL.TIN = COMPANY_DOMAIN.TIN
AND COMPANY_DOMAIN.DOMAIN_NAME = 'Banking';

CREATE TABLE TEMP9 AS
SELECT DISTINCT HELPS.HELPED AS TIN
FROM SMALL, COMPANY_DOMAIN, HELPS
WHERE SMALL.TIN = COMPANY_DOMAIN.TIN
AND HELPS.HELPER = SMALL.TIN
AND COMPANY_DOMAIN.DOMAIN_NAME = 'IT';

CREATE TABLE ANSWER7 AS 
SELECT DISTINCT TIN
FROM TEMP8
INTERSECT
SELECT DISTINCT TIN
FROM TEMP9
ORDER BY TIN ASC;

PROMPT ANSWER7
SELECT * FROM ANSWER7;



spool off
