-- Replace zk1 with your NetID
@dataSetupScript07.sql

spool spool07.txt

PROMPT jy3555

/*

YOU START YOU’RE ANSWERS AFTER THE END OF THIS COMMENT BLOCK

ANSWER0 is an example to show you the structure of what you need to produce, unless instructed otherwise in the assignment. Please read carefully what you are asked to do.

Insert your solution for ANSWERX between the string -- ANSWERX and the string PROMPT ANSWERX

*/

-- ANSWER0
-- Answer 0 represents a sample query that uses the temp table TEMP0 just to demonstrate the usage of temp table.
-- ANSWER0
CREATE TABLE TEMP0
AS SELECT *
FROM SMALL;

CREATE TABLE ANSWER0
AS SELECT DISTINCT TIN
FROM TEMP0
ORDER BY TIN DESC;

PROMPT ANSWER0
SELECT * FROM ANSWER0;

-- ANSWER1
CREATE TABLE TEMP1
AS SELECT DISTINCT TIN
FROM BIG
WHERE FAMILYNAME IS NULL AND PERSONALNAME IS NULL;

CREATE TABLE ANSWER1
AS SELECT DISTINCT COMPANY.REGNUMBER, COMPANY.TIN
FROM COMPANY, TEMP1
WHERE COMPANY.TIN = TEMP1.TIN
ORDER BY REGNUMBER ASC, TIN ASC;

PROMPT ANSWER1
SELECT * FROM ANSWER1;

-- ANSWER2
CREATE TABLE TEMP2
AS SELECT DISTINCT BIG.TIN, MANAGER.SALARY / BIG.COMPANY_VALUE AS RATIO
FROM BIG, MANAGER
WHERE BIG.FAMILYNAME = MANAGER.FAMILYNAME AND BIG.PERSONALNAME = MANAGER.PERSONALNAME;

CREATE TABLE ANSWER2
AS SELECT DISTINCT TIN, RATIO
FROM TEMP2
WHERE RATIO > 0.1
ORDER BY TIN ASC, RATIO ASC;

PROMPT ANSWER2
SELECT * FROM ANSWER2;

-- ANSWER3
CREATE TABLE TEMP3
AS SELECT DISTINCT TIN, COUNT(DOMAIN_NAME) AS COUNTER
FROM COMPANY_DOMAIN
GROUP BY TIN;

CREATE TABLE ANSWER3
AS SELECT DISTINCT TIN
FROM TEMP3
WHERE TIN >= '20000000' AND COUNTER >= 3;

PROMPT ANSWER3
SELECT * FROM ANSWER3;

-- ANSWER4
CREATE TABLE TEMP4
AS SELECT DISTINCT DOMAIN_NAME, TIN
FROM COMPANY_DOMAIN
WHERE TIN = '99448276';

CREATE TABLE TEMP5
AS SELECT * FROM 

PROMPT ANSWER4
SELECT * FROM ANSWER4;


-- ANSWER5
DELETE FROM COMPANY
WHERE TIN = '74939103'


PROMPT ANSWER5
SELECT * FROM Company;

-- ANSWER6
UPDATE BIG
SET FAMILYNAME = 'ALDRIN', PERSONALNAME = 'MICKEY'
WHERE TIN = '95499546';

PROMPT ANSWER6
SELECT * FROM Company;
SELECT * FROM Big;
SELECT * FROM Manager;



-- ANSWER7
DELETE FROM BIG
WHERE TIN = '35983220';

INSERT INTO SMALL(TIN) VALUES('35983220');

PROMPT ANSWER7
SELECT * FROM Company;
SELECT * FROM Big;
SELECT * FROM Small;

-- ANSWER8
INSERT INTO HELPS(HELPER, HELPED) VALUES ('74939103', '90309251');

PROMPT ANSWER8
SELECT * FROM HELPS;

-- ANSWER9
PROMPT ANSWER9
/*
Write your solution below
*/
CREATE TABLE TEMP6 AS
SELECT *
FROM R LEFT OUTER JOIN S
ON R.A = S.C AND R.B = S.D;

CREATE TABLE ANSWER9 AS
SELECT DISTINCT A,B
FROM TEMP6
WHERE C IS NULL AND D IS NULL
ORDER BY A ASC, B ASC;

spool off
